name: Update Stars
on:
  schedule:
    - cron: "0 0 * * *" # 每天自动同步一次
  workflow_dispatch: # 支持手动点击运行

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: "README.md"
          writeTo: "README.md"
          stars: 5 # 显示最近点赞的5个项目
